name: Build

on:
  push:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: jkostov/functions-api

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: env GOOS=linux GOARCH=amd64 go build -o build/functions-api -v cmd/app/main.go
      
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
